"use client";
import {useEffect,useMemo,useState} from "react";
import {SHOPPING_PRODUCT_NAMES} from "@/lib/shopping-products";
import {ArrowLeft,ArrowRight,BarChart3,Check,ChevronRight,Eye,EyeOff,Plus,Search,ShoppingBasket,Store,TrendingDown,TrendingUp,X} from "lucide-react";

type PurchaseItem={id:string;name:string;brand:string;packageSize:string;category:string;quantity:number;price:number};
type Purchase={id:string;market:string;date:string;items:PurchaseItem[];total:number;financialAdded?:boolean;legacyId?:string};
const brl=(n:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number.isFinite(n)?n:0);
const moneyInput=(value:string)=>{const digits=value.replace(/\D/g,'');return digits?new Intl.NumberFormat('pt-BR',{minimumFractionDigits:2}).format(Number(digits)/100):''};
const numberValue=(value:string)=>Number(value.replace(/[.]/g,'').replace(',','.'))||0;
const normalize=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLocaleLowerCase('pt-BR');
const productKey=(item:Partial<PurchaseItem>)=>[item.name,item.brand,item.packageSize].map(value=>normalize(String(value||''))).join('|');
const isoToday=()=>new Intl.DateTimeFormat('en-CA').format(new Date());

export default function PurchasesPage({onFinish,hidden,onTogglePrivacy}:{onFinish:(data:any)=>void;hidden:boolean;onTogglePrivacy:()=>void}){
 const [purchases,setPurchases]=useState<Purchase[]>([]);const [month,setMonth]=useState(isoToday().slice(0,7));const [editor,setEditor]=useState<any>(null);const [detail,setDetail]=useState<Purchase|null>(null);const [query,setQuery]=useState('');const [market,setMarket]=useState('Todos');const [selectedKey,setSelectedKey]=useState('');const [pendingDelete,setPendingDelete]=useState<Purchase|null>(null);
 useEffect(()=>{try{const current=JSON.parse(localStorage.getItem('juntos-purchases-v2')||'[]');if(current.length){setPurchases(current);return}const legacy=JSON.parse(localStorage.getItem('juntos-shopping-lists')||'[]');const migrated=legacy.filter((list:any)=>list.finalizedAt).map((list:any)=>({id:'legacy-'+list.id,legacyId:list.id,market:list.name,date:list.purchaseDate||String(list.finalizedAt).slice(0,10),items:(list.items||[]).filter((item:any)=>item.bought!==false).map((item:any)=>({id:String(item.id),name:item.name||'',brand:item.brand||'',packageSize:item.packageSize||'',category:item.category||'Mercado',quantity:Math.max(0,Number(item.quantity)||0),price:Math.max(0,Number(item.price)||0)})),total:Number(list.totalPaid)||0,financialAdded:true})).filter((item:any)=>item.market&&item.date&&item.items.length);if(migrated.length){localStorage.setItem('juntos-purchases-v2',JSON.stringify(migrated));setPurchases(migrated)}}catch{}},[]);
 const persist=(next:Purchase[])=>{setPurchases(next);localStorage.setItem('juntos-purchases-v2',JSON.stringify(next))};const show=(value:number)=>hidden?'••••••':brl(value);
 const records=useMemo(()=>purchases.flatMap(purchase=>purchase.items.map(item=>({...item,purchaseId:purchase.id,date:purchase.date,market:purchase.market}))).sort((a,b)=>a.date.localeCompare(b.date)),[purchases]);
 const compared=useMemo(()=>records.map((item,index)=>{const previous=records.slice(0,index).reverse().find(other=>productKey(other)===productKey(item));const delta=previous?item.price-previous.price:null;return {...item,previous,delta,saving:delta!==null&&delta<0?Math.abs(delta)*item.quantity:0}}),[records]);
 const monthPurchases=purchases.filter(item=>item.date.startsWith(month));const monthRecords=compared.filter(item=>item.date.startsWith(month));const spent=monthPurchases.reduce((sum,item)=>sum+item.total,0);const savings=monthRecords.reduce((sum,item)=>sum+item.saving,0);const wins=monthRecords.filter(item=>item.saving>0).sort((a,b)=>b.saving-a.saving);const rises=monthRecords.filter(item=>Number(item.delta)>0).sort((a,b)=>Number(b.delta)-Number(a.delta));
 const markets=['Todos',...Array.from(new Set(purchases.map(item=>item.market)))];const products=Array.from(new Map(records.map(item=>[productKey(item),item])).entries());const knownProductNames=Array.from(new Set([...SHOPPING_PRODUCT_NAMES,...products.map(([,item])=>item.name)]));const filtered=products.filter(([,item])=>(!query||normalize(item.name).includes(normalize(query)))&&(market==='Todos'||records.some(record=>productKey(record)===productKey(item)&&record.market===market)));const currentKey=selectedKey&&filtered.some(([key])=>key===selectedKey)?selectedKey:filtered[0]?.[0]||'';const selected=products.find(([key])=>key===currentKey)?.[1];const history=selected?records.filter(item=>productKey(item)===currentKey):[];
 const changeMonth=(offset:number)=>{const date=new Date(month+'-01T12:00:00');date.setMonth(date.getMonth()+offset);setMonth(new Intl.DateTimeFormat('en-CA').format(date).slice(0,7))};
 const openEditor=()=>setEditor({market:'',date:isoToday(),items:[{id:String(Date.now()),name:'',brand:'',packageSize:'',category:'Alimentos',quantity:'1',price:''}]});const updateItem=(id:string,key:string,value:string)=>setEditor({...editor,items:editor.items.map((item:any)=>item.id===id?{...item,[key]:value}:item)});const draftTotal=editor?.items.reduce((sum:number,item:any)=>sum+Math.max(0,Number(item.quantity)||0)*numberValue(item.price),0)||0;
 const save=(event:any)=>{event.preventDefault();const known=purchases.find(item=>normalize(item.market)===normalize(editor.market));const items=editor.items.map((item:any)=>({...item,name:item.name.trim(),brand:item.brand.trim(),packageSize:item.packageSize.trim(),quantity:Number(item.quantity),price:numberValue(item.price)})).filter((item:PurchaseItem)=>item.name&&item.quantity>0&&item.price>=0);if(!editor.market.trim()||!editor.date||!items.length)return;const existing=purchases.find(item=>item.id===editor.id);const purchase:Purchase={id:existing?.id||'purchase-'+Date.now(),market:known?.market||editor.market.trim(),date:editor.date,items,total:items.reduce((sum:number,item:PurchaseItem)=>sum+item.quantity*item.price,0),financialAdded:Boolean(existing?.financialAdded),legacyId:existing?.legacyId};persist(existing?purchases.map(item=>item.id===purchase.id?purchase:item):[purchase,...purchases]);setEditor(null);setDetail(purchase)};
 const editPurchase=(purchase:Purchase)=>{setDetail(null);setEditor({...purchase,items:purchase.items.map(item=>({...item,quantity:String(item.quantity),price:item.price.toFixed(2).replace('.',',')}))})};
 const deletePurchase=(purchase:Purchase)=>setPendingDelete(purchase);const confirmDelete=()=>{if(!pendingDelete)return;persist(purchases.filter(item=>item.id!==pendingDelete.id));setPendingDelete(null);setDetail(null)};
 const addFinancial=(purchase:Purchase)=>{if(purchase.financialAdded)return;onFinish({title:`Compra no ${purchase.market}`,category:'Mercado',person:'Casal',account:'Carteira',payment:'Pix',card:'',date:purchase.date,value:purchase.total,type:'out',icon:'−',status:'Pago'});const next=purchases.map(item=>item.id===purchase.id?{...item,financialAdded:true}:item);persist(next);setDetail({...purchase,financialAdded:true})};
 const maxPrice=Math.max(1,...history.map(item=>item.price));
 return <div className="page-stack purchases-v2"><header className="purchases-v2-header"><div><p>CONTROLE DE COMPRAS</p><h1>Compras</h1><span>Acompanhe preços, mercados e sua economia ao longo do tempo.</span></div><div><button className="ghost" onClick={onTogglePrivacy}>{hidden?<Eye size={17}/>:<EyeOff size={17}/>} {hidden?'Mostrar valores':'Ocultar valores'}</button><button className="primary" onClick={openEditor}><Plus size={17}/> Registrar compra</button></div></header>
 <nav className="purchase-month"><button onClick={()=>changeMonth(-1)}><ArrowLeft size={16}/></button><b>{new Date(month+'-01T12:00:00').toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</b><button onClick={()=>changeMonth(1)}><ArrowRight size={16}/></button></nav>
 <section className="purchase-kpis"><article><span>Gasto no mês</span><strong>{show(spent)}</strong><small>{monthPurchases.length} compras</small></article><article><span>Economia identificada</span><strong>{show(savings)}</strong><small>{compared.some(item=>item.previous)?'Comparada à compra anterior':'Histórico ainda insuficiente'}</small></article><article><span>Produtos comprados</span><strong>{monthRecords.reduce((sum,item)=>sum+item.quantity,0)}</strong><small>{monthRecords.length} registros</small></article><article><span>Melhor economia</span><strong>{wins[0]?show(wins[0].saving):'—'}</strong><small>{wins[0]?.name||'Sem comparação no período'}</small></article></section>
 {!purchases.length?<section className="card purchase-empty"><ShoppingBasket/><h2>Nenhuma compra registrada ainda.</h2><p>Registre uma compra real para começar seu histórico de preços.</p><button className="primary" onClick={openEditor}>Registrar primeira compra</button></section>:<><section className="purchase-dashboard"><article className="card purchase-highlight"><h2><TrendingDown/> Maiores economias</h2>{wins.length?wins.slice(0,5).map(item=><div key={item.purchaseId+item.id}><span><b>{item.name}</b><small>{show(item.previous!.price)} → {show(item.price)} · {item.market}</small></span><strong>↓ {show(item.saving)}</strong></div>):<p>Ainda não há economia comparável neste período.</p>}</article><article className="card purchase-highlight rises"><h2><TrendingUp/> Maiores altas</h2>{rises.length?rises.slice(0,5).map(item=><div key={item.purchaseId+item.id}><span><b>{item.name}</b><small>{show(item.previous!.price)} → {show(item.price)}</small></span><strong>↑ {item.previous!.price?((Number(item.delta)/item.previous!.price)*100).toFixed(1):'0'}%</strong></div>):<p>Nenhuma alta comparável neste período.</p>}</article></section>
 <section className="card purchases-recent"><div className="purchase-title"><div><h2>Compras recentes</h2><p>Compras efetivamente registradas</p></div><Store/></div>{monthPurchases.length?<div>{monthPurchases.slice(0,8).map(item=><button key={item.id} onClick={()=>setDetail(item)}><time>{new Date(item.date+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'short'}).toUpperCase()}</time><span><b>{item.market}</b><small>{item.items.length} produtos</small></span><strong>{show(item.total)}</strong><ChevronRight/></button>)}</div>:<p className="purchase-state">Nenhuma compra neste mês.</p>}</section>
 <section className="card product-history"><div className="purchase-title"><div><h2>Histórico de preços</h2><p>Mesmo produto, marca e embalagem</p></div><BarChart3/></div><div className="purchase-filters"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar produto..."/></label><select value={market} onChange={e=>setMarket(e.target.value)}>{markets.map(item=><option key={item}>{item}</option>)}</select></div>{filtered.length?<><div className="product-tabs">{filtered.map(([key,item])=><button className={key===currentKey?'active':''} onClick={()=>setSelectedKey(key)} key={key}>{item.name}{item.packageSize&&` ${item.packageSize}`}</button>)}</div>{selected&&<div className="history-panel"><h3>{selected.name} {selected.packageSize}</h3>{history.length>1?<div className="price-chart">{history.slice(-10).map(item=><div key={item.purchaseId+item.id}><span>{show(item.price)}</span><i style={{height:`${Math.max(10,item.price/maxPrice*100)}%`}}/><small>{new Date(item.date+'T12:00:00').toLocaleDateString('pt-BR',{month:'short'})}<br/>{item.market}</small></div>)}</div>:<p className="purchase-state">Registre mais compras deste produto para visualizar a evolução.</p>}<div className="history-stats"><span>Atual<b>{show(history.at(-1)?.price||0)}</b></span><span>Menor<b>{show(Math.min(...history.map(item=>item.price)))}</b></span><span>Maior<b>{show(Math.max(...history.map(item=>item.price)))}</b></span><span>Média<b>{show(history.reduce((sum,item)=>sum+item.price,0)/history.length)}</b></span></div><div className="market-comparison"><h4>Comparação por mercado</h4>{Array.from(new Map(history.slice().reverse().map(item=>[normalize(item.market),item])).values()).map(item=><div key={item.market}><span>{item.market}</span><b>{show(item.price)}</b></div>)}</div></div>}</>:<p className="purchase-state">Nenhum produto encontrado.</p>}</section></>}
 {editor&&<div className="modal-backdrop"><form className="modal purchase-v2-editor" onSubmit={save}><header><div><span>{editor.id?'EDITAR COMPRA':'REGISTRAR COMPRA'}</span><h2>{editor.id?'Editar compra':'Nova compra'}</h2><p>Cadastre somente itens que já foram comprados.</p></div><button type="button" onClick={()=>setEditor(null)}><X/></button></header><div className="purchase-base"><label>Mercado<input list="markets-used" value={editor.market} onChange={e=>setEditor({...editor,market:e.target.value})} required/><datalist id="markets-used">{markets.slice(1).map(item=><option value={item} key={item}/>)}</datalist></label><label>Data<input type="date" value={editor.date} onChange={e=>setEditor({...editor,date:e.target.value})} required/></label></div><div className="purchase-editor-items">{editor.items.map((item:any,index:number)=><div key={item.id}><b>Produto {index+1}</b><input list="known-products" value={item.name} onChange={e=>updateItem(item.id,'name',e.target.value)} placeholder="Produto" required/><datalist id="known-products">{knownProductNames.map(name=><option key={name} value={name}/>)}</datalist><input value={item.brand} onChange={e=>updateItem(item.id,'brand',e.target.value)} placeholder="Marca (opcional)"/><input value={item.packageSize} onChange={e=>updateItem(item.id,'packageSize',e.target.value)} placeholder="Embalagem: 500g, 2L..."/><input type="number" min="0.01" step="0.01" value={item.quantity} onChange={e=>updateItem(item.id,'quantity',e.target.value)} placeholder="Qtd." required/><input value={item.price} onChange={e=>updateItem(item.id,'price',moneyInput(e.target.value))} inputMode="decimal" placeholder="Preço pago" required/>{editor.items.length>1&&<button type="button" onClick={()=>setEditor({...editor,items:editor.items.filter((entry:any)=>entry.id!==item.id)})}><X/></button>}</div>)}</div><button type="button" className="ghost" onClick={()=>setEditor({...editor,items:[...editor.items,{id:String(Date.now()),name:'',brand:'',packageSize:'',category:'Alimentos',quantity:'1',price:''}]})}><Plus/> Adicionar produto</button><div className="purchase-draft-total"><span>Total da compra</span><strong>{show(draftTotal)}</strong></div><footer><button type="button" className="ghost" onClick={()=>setEditor(null)}>Cancelar</button><button className="primary"><Check/> Salvar compra</button></footer></form></div>}
 {pendingDelete&&<div className="modal-backdrop purchase-delete-backdrop" onMouseDown={event=>event.target===event.currentTarget&&setPendingDelete(null)}><div className="modal purchase-delete-modal" role="alertdialog" aria-modal="true" aria-labelledby="purchase-delete-title"><div className="purchase-delete-icon"><ShoppingBasket/></div><h2 id="purchase-delete-title">Excluir esta compra?</h2><p>A compra no <b>{pendingDelete.market}</b>, no valor de <b>{show(pendingDelete.total)}</b>, será removida do histórico de preços.</p>{pendingDelete.financialAdded&&<div className="purchase-delete-warning"><b>Atenção</b><span>A despesa enviada ao financeiro continuará em Transações e deverá ser excluída separadamente.</span></div>}<div className="purchase-delete-actions"><button className="ghost" onClick={()=>setPendingDelete(null)}>Cancelar</button><button className="purchase-delete-confirm" onClick={confirmDelete}><X size={16}/> Excluir compra</button></div></div></div>} {detail&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setDetail(null)}><div className="modal purchase-v2-detail"><header><div><span>COMPRA REGISTRADA</span><h2>{detail.market}</h2><p>{new Date(detail.date+'T12:00:00').toLocaleDateString('pt-BR',{dateStyle:'long'})}</p></div><button onClick={()=>setDetail(null)}><X/></button></header>{detail.items.map(item=><div className="purchase-detail-row" key={item.id}><span><b>{item.name}</b><small>{item.quantity} × {show(item.price)} {item.packageSize&&`· ${item.packageSize}`}</small></span><strong>{show(item.quantity*item.price)}</strong></div>)}<div className="purchase-detail-total"><span>Total</span><strong>{show(detail.total)}</strong></div><div className="purchase-detail-actions"><button className="ghost danger" onClick={()=>deletePurchase(detail)}><X size={16}/> Excluir</button><button className="ghost" onClick={()=>editPurchase(detail)}>Editar compra</button><button className="primary purchase-to-finance" disabled={detail.financialAdded} onClick={()=>addFinancial(detail)}>{detail.financialAdded?'Adicionada ao financeiro':'Adicionar como despesa'}</button></div></div></div>}
 </div>
}